package com.mercadolibre.academy.fidelizacion.modelo.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idCliente;
	private Direccion direccion;
	private String nombre;
	private String apellido;
	private String dni;
	private String telefono;
	private String mail;
	private Date fechaNacimiento;
	private Date fechaAlta;
	private int puntosAcumulados;
	private Set<Compra> compras = new HashSet<Compra>(0);
	private Set<Puntos> puntos = new HashSet<Puntos>(0);
	private Set<Canje> canjes = new HashSet<Canje>(0);

	public Cliente() {
	}

	public Cliente(Direccion direccion, String nombre, String apellido, String dni, Date fechaAlta,
			int puntosAcumulados) {
		this.direccion = direccion;
		this.nombre = nombre;
		this.apellido = apellido;
		this.dni = dni;
		this.fechaAlta = fechaAlta;
		this.puntosAcumulados = puntosAcumulados;
	}

	public Cliente(Direccion direccion, String nombre, String apellido, String dni, String telefono, String mail,
			Date fechaNacimiento, Date fechaAlta, int puntosAcumulados, Set<Compra> compras, Set<Puntos> puntos, Set<Canje> canjes) {
		this.direccion = direccion;
		this.nombre = nombre;
		this.apellido = apellido;
		this.dni = dni;
		this.telefono = telefono;
		this.mail = mail;
		this.fechaNacimiento = fechaNacimiento;
		this.fechaAlta = fechaAlta;
		this.puntosAcumulados = puntosAcumulados;
		this.compras = compras;
		this.puntos = puntos;
		this.canjes = canjes;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public Direccion getDireccion() {
		return this.direccion;
	}

	public void setDireccion(Direccion direccion) {
		this.direccion = direccion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public int getPuntosAcumulados() {
		return this.puntosAcumulados;
	}

	public void setPuntosAcumulados(int puntosAcumulados) {
		this.puntosAcumulados = puntosAcumulados;
	}

	public Set<Compra> getCompras() {
		return this.compras;
	}

	public void setCompras(Set<Compra> compras) {
		this.compras = compras;
	}

	public Set<Puntos> getPuntos() {
		return this.puntos;
	}

	public void setPuntos(Set<Puntos> puntos) {
		this.puntos = puntos;
	}

	public Set<Canje> getCanjes() {
		return this.canjes;
	}

	public void setCanjes(Set<Canje> canjes) {
		this.canjes = canjes;
	}

}
